name: snack_pack
description: A beautiful and customizable animated snack bar package for Flutter. Display top-aligned snack bars with smooth animations and swipe-to-dismiss functionality.
version: 1.0.0
homepage: https://github.com/dhirajnikam/snack_pack
repository: https://github.com/dhirajnikam/snack_pack
issue_tracker: https://github.com/dhirajnikam/snack_pack/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
